<a href="https://colab.research.google.com/github/YaCpotato/python/blob/master/PorkerHand_XG_LGBM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

やること  
* XGBoost理論調査
* LightGBM CatBoostとの比較

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [4]:
%cd drive/'My Drive'/'Colab Notebooks'/

/content/drive/My Drive/Colab Notebooks


In [5]:
import pandas as pd
import io
train = pd.read_csv('./poker-hand-training-true.csv', header=None)
test = pd.read_csv('./poker-hand-testing.csv', header=None)
train.head()
test.head()

0   1   2   3   4   5   6   7   8   9   10
0   1   1   1  13   2   4   2   3   1  12   0
1   3  12   3   2   3  11   4   5   2   5   1
2   1   9   4   6   1   4   3   2   3   9   1
3   1   4   3  13   2  13   2   1   3   6   1
4   3  10   2   7   1   2   2  11   4   9   0

こういうデータに対して(どういうデータか説明もできない)するべき前処理が未だうかばない筆者です。アドバイス求む。  
PandasのDataFrameも使おうとしたがまだ機械学習のいちプロセスで使い通せない段階

# データを整形する
* ラベルデータの取り出し(正確には代入してから削除してる)
* 学習データ、テストデータの分割

In [6]:
from sklearn import preprocessing
from keras.utils import np_utils
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import normalize

train_Y = train[:][10]
test_Y = test[:][10]

X_train, X_test, Y_train, Y_test = train_test_split(train, train_Y,train_size=0.7)


X_train.drop(10,axis=1,inplace=True)
X_test.drop(10,axis=1,inplace=True)
print(X_train.shape,Y_train.shape,X_test.shape,Y_test.shape)

Using TensorFlow backend.


(17507, 10) (17507,) (7503, 10) (7503,)


/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:4117: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [0]:
import xgboost as xgb
from sklearn.model_selection import GridSearchCV

In [0]:
clf = xgb.XGBClassifier()

In [0]:
clf_cv = GridSearchCV(clf, {'max_depth': [2,4,6], 'n_estimators': [50,100,200]}, verbose=1)

In [0]:
print(X_train.shape,Y_train.shape)
clf_cv.fit(X_train, Y_train,verbose=1)

(17507, 10) (17507,)
Fitting 3 folds for each of 9 candidates, totalling 27 fits


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:657: Warning: The least populated class in y has only 2 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  27 out of  27 | elapsed:  2.7min finished


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                     colsample_bylevel=1, colsample_bynode=1,
                                     colsample_bytree=1, gamma=0,
                                     learning_rate=0.1, max_delta_step=0,
                                     max_depth=3, min_child_weight=1,
                                     missing=None, n_estimators=100, n_jobs=1,
                                     nthread=None, objective='binary:logistic',
                                     random_state=0, reg_alpha=0, reg_lambda=1,
                                     scale_pos_weight=1, seed=None, silent=None,
                                     subsample=1, verbosity=1),
             iid='warn', n_jobs=None,
             param_grid={'max_depth': [2, 4, 6],
                         'n_estimators': [50, 100, 200]},
             pre_dispatch='2*n_jobs', refit=True, retur

In [0]:
# 改めて最適パラメータで学習
clf = xgb.XGBClassifier(**clf_cv.best_params_)
clf.fit(X_train, Y_train,verbose=1)

# 学習モデルの評価
from sklearn.metrics import confusion_matrix,classification_report
pred = clf.predict(X_test)
print (confusion_matrix(Y_test, pred))
print (classification_report(Y_test, pred))

[[3221  591    1    0    0    0    0    0    0]
 [1147 1948   12    2    1    0    0    0    0]
 [  28  315   11    1    0    0    0    0    0]
 [   5  145    1    9    0    0    0    0    0]
 [   2   29    0    0    0    0    0    0    0]
 [  16    1    0    0    0    1    0    0    0]
 [   0    9    0    1    0    0    0    0    0]
 [   0    3    0    0    0    0    0    0    0]
 [   1    1    0    0    0    1    0    0    0]]
              precision    recall  f1-score   support

           0       0.73      0.84      0.78      3813
           1       0.64      0.63      0.63      3110
           2       0.44      0.03      0.06       355
           3       0.69      0.06      0.10       160
           4       0.00      0.00      0.00        31
           5       0.50      0.06      0.10        18
           6       0.00      0.00      0.00        10
           7       0.00      0.00      0.00         3
           9       0.00      0.00      0.00         3

    accuracy             

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [0]:
from sklearn.ensemble import RandomForestClassifier
RFCmodel = RandomForestClassifier(n_estimators=100,random_state=0)
RFCmodel.fit(X_train,Y_train)
pred = RFCmodel.predict(X_test)
print(RFCmodel.score(X_test,Y_test))

0.5949620151939224


In [0]:
import lightgbm as lgb

In [20]:
import numpy as np
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
Y_train = Y_train.astype('float32')
Y_test = Y_test.astype('float32')

lgb_model = lgb.LGBMClassifier()
lgb_model.fit(X_train, Y_train)

# テストデータを予測する
Y_pred = lgb_model.predict_proba(X_test)
Y_pred_max = np.argmax(Y_pred, axis=1)  # 最尤と判断したクラスの値にする

# 精度 (Accuracy) を計算する
from sklearn.metrics import confusion_matrix,classification_report
print (confusion_matrix(Y_test, pred))
print (classification_report(Y_test, pred))
# 精度 (Accuracy) を計算する
accuracy = sum(Y_test == pred_max) / len(Y_test)
print(accuracy)



ValueError: ignored